### ISSUE TITLE
RMD Check Test Issue

### ISSUE THREAD

**Issue by Michiru0206** [cbasnetchettri/animeR#2]
@rudeboybert

We ran the RMD Check test and got one note. How can we solve this issue? 
```
search_anime: no visible binding for global variable ‘anime’
search_anime: no visible binding for global variable ‘title’
search_anime: no visible binding for global variable ‘synopsis’
Undefined global functions or variables:
   anime synopsis title
Consider adding
importFrom("graphics", "title")
to your NAMESPACE file.
```

**Comment by rudeboybert** [comment]
Hey @Michiru0206 I think mimicking what was done [here](https://github.com/ajhaller/IPEDS/blob/main/R/acceptance_rate.R#L1) should do the trick

**Comment by Michiru0206** [comment]
After adding `globalVariable()`, it passed RMD Check test. Thank you so much!
